# 사이트 설정
title: circleGiven's LAB
description: 놀 새로워, 배우는건 짜릿해
# 프로젝트 별 페이지 만들때 사용
baseurl: ""
# 내 URL
url: https://circleGiven.github.io
# dev
#url: "http://localhost:3000"

# User settings
username: circleGiven
user_description: Junior developer
email: circlegiven@gmail.com
github_username: circleGiven
gplus_username:  circlegiven
linkedin_username:  wonjune
disqus_username: circlegiven

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']